FROM debian:bookworm
RUN apt -qq upgrade -y && apt -qq update -y && apt -q install vim net-tools mariadb-server -y

RUN mkdir -p /var/log/mysql && chown mysql:mysql /var/log/mysql
RUN mkdir -p /var/sql_data && chown mysql:mysql /var/sql_data

COPY --chmod=644 conf/my.cnf /etc/mysql/
COPY --chmod=644 conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY --chmod=744 tools/initial.sh /initial.sh
COPY --chmod=744 tools/set_updb.sh /set_updb.sh

EXPOSE 3306

ENTRYPOINT ["/initial.sh"]
#ENTRYPOINT ["bash"]
